apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind--argocd
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/dev-kind'
    path: argocd
    targetRevision: 0.0.1
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
