apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind--kuma-zone
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/dev-kind'
    path: kuma-zone
    targetRevision: master
  destination:
    name: kind
    namespace: kuma-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
