apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind--pihole
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/dev-kind'
    path: pihole
    targetRevision: master
  destination:
    name: in-cluster
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
