apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind--prometheus
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/dev-kind'
    path: prometheus
    targetRevision: 0.0.1
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
