apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind--vault
  namespace: argocd
spec:
  project: kind
  source:
    repoURL: 'https://github.com/amanibhavam/dev-kind'
    path: vault
    targetRevision: master
  destination:
    name: kind
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
